import './globals.css'
import { Nunito } from 'next/font/google'

const inter = Nunito({
  weight: ['200' ,'400', '500', '600', '700', '800'],
  subsets: ['latin'],
})

export const metadata = {
  title: 'Air Conditioning 123',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
